# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 472c69cccea7db4dd5a7f7a412877399da7b367908ced8335bd4607c0dea2ede0e8e0b1afc48ddd0f66c9242ccfac702d35d5c206928231aa4a1b3d19372b6c9

test:
  secret_key_base: 31f35ac4469972ae524019192bdbeaa8558560a963145c342732ddfa4983cf6b721e7ee83d8b6942dbf08e84207f79b0eb1d906f24c9deb52fc6e7ea4c091b61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
